services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'projector_l8'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
    - '3308:3308'
    expose:
    - '3308'
    command: --init-file /data/application/init.sql
    volumes:
    - ./data:/var/lib/mysql

  php:
    build:
      context: ./php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html